import { mkdir, writeFile } from 'node:fs/promises';

const SOURCE = 'https://raw.githubusercontent.com/profesorm/hsk30/main/data/hsk_vocabulary.csv';
const OUTPUT = new URL('../src/data/generated-hsk.json', import.meta.url);

const LEVELS = new Map([
  ['一级', 1],
  ['二级', 2],
  ['三级', 3],
  ['四级', 4],
  ['五级', 5],
  ['六级', 6],
]);

function parseLevel(levelName) {
  for (const [label, level] of LEVELS) {
    if (levelName.startsWith(label)) return level;
  }
  return null;
}

function cleanDisplayWord(sourceWord) {
  return sourceWord.replace(/[0-9]+$/u, '');
}

async function main() {
  console.log(`Fetching ${SOURCE}`);
  const response = await fetch(SOURCE);
  if (!response.ok) {
    throw new Error(`HSK source download failed: ${response.status} ${response.statusText}`);
  }

  const text = await response.text();
  const lines = text.replace(/^\uFEFF/u, '').trim().split(/\r?\n/u);
  const header = lines.shift();
  if (header !== 'type,word,pinyin,cixing,sort,levelName') {
    throw new Error(`Unexpected CSV header: ${header}`);
  }

  const words = [];
  for (const line of lines) {
    const [type, sourceWord, pinyin, partOfSpeechZh, sortRaw, levelName] = line.split(',');
    if (!sourceWord || !pinyin || !sortRaw || !levelName) continue;

    const level = parseLevel(levelName);
    if (!level) continue; // MVP app scope: HSK 1~6

    const sort = Number(sortRaw);
    words.push({
      id: `hsk${level}-${String(sort).padStart(4, '0')}`,
      level,
      sourceWord,
      word: cleanDisplayWord(sourceWord),
      pinyin,
      partOfSpeechZh: partOfSpeechZh || '',
      sort,
      levelName,
      sourceType: type,
    });
  }

  await mkdir(new URL('../src/data/', import.meta.url), { recursive: true });
  await writeFile(
    OUTPUT,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        source: SOURCE,
        sourceProject: 'https://github.com/profesorm/hsk30',
        officialSource: 'https://www.chinesetest.cn/',
        scope: 'HSK 1-6',
        count: words.length,
        words,
      },
      null,
      2,
    ),
    'utf8',
  );

  console.log(`Wrote ${words.length} words to src/data/generated-hsk.json`);
  console.log('Note: Korean meanings/examples are curated separately and are not generated by this script.');
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
